[package]
name="webp"
version="0.0.2"
description="WebP is a modern image format that provides superior lossless and lossy compression for images on the web"
readme = "README.md"
repository = "https://github.com/wapm-packages/libwebp"

[[module]]
name="cwebp"
source="cwebp.wasm"
abi = "emscripten"

[[module]]
name="dwebp"
source="dwebp.wasm"
abi = "emscripten"

[[command]]
name="cwebp"
module="cwebp"

[[command]]
name="dwebp"
module="dwebp"
